### ISSUE TITLE
Custom spoken names for slots in disk-swap list.

### ISSUE THREAD

**Issue by kerobaros** [FujiNetWIFI/fujinet-config-old#13]
Enhancement idea: Wondering if, instead of the default of 'Disk 1', 'Disk 2', etc., we could add a custom description to each disk we add to the list. 

For example, TAB down to the Drive Slots, press [D]escription, prompt for text. 'Game 1', 'Game 2', 'Save Disk', etc. Then when pressing the disk-swap button, SAM would speak the custom description instead.

Follow-up thought: does SAM take raw text? or only phonemes?

**Comment by jhusak** [comment]
I thoutht about another extension to this idea. There are some open source speech synthesizers, like espeak (I remember it was small, but now it got big because of dictionaries)
The second extension is "sexy female voice", only samples "disk" "1"-"8"

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
