### ISSUE TITLE
HSIO index changes aren't doing anything?

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-config-old#16]
Adjusting the "HSIO" (high speed I/O) index via the web config (or by manually editing the INI file on the SD card and rebooting the #FujiNet) does not appear to affect the transfer speeds.

- Fujinet Version: `0.5.77c13818 2020-10-05 01:27:16`
- Config Version: `2.5.2020-08-25`
- Atari 1200XL with Bob Woolley hacked XL OS (though when I use high speed I/O on an SIO2SD 1.3 device, it works great)

Any speed I've chosen -- the default(?) of 6: 67Kb; the fastest 0: 124Kb; the slowest 9: 55Kb -- all seem to result in the same transfer speed, when booting CONFIG off of the #FujiNet, or booting an ATR or XEX off of the local SD storage.

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
