### ISSUE TITLE
"Loading Binary Files from N: Device" test failure: INVALID FILE NAME

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-config-old#17]
I attempted to follow the [current revision](https://github.com/FujiNetWIFI/fujinet-platformio/wiki/Loading-Binary-Files-from-N:-Device/56fe2c9a4666b4455e9d12b2621663fc7ebc83d8) of the ["Loading Binary Files from N: Device"](https://github.com/FujiNetWIFI/fujinet-platformio/wiki/Loading-Binary-Files-from-N:-Device/56fe2c9a4666b4455e9d12b2621663fc7ebc83d8) test.

At step 11 ("Try loading Buried Bucks"), after issuing "N:BURIEDBU" to DOS XL, I received an "INVALID FILE NAME" error.

**Comment by billkendrick** [comment]
Issuing "NPWD" results in "HTTP://ATARI-APPS.IRATA.ONLINE/".  Running "NDIR" with either "*.*" or nothing ([Return]) results in a brief burst of SIO noise, and no output (return to "D1:" DOS XL prompt).

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
