### ISSUE TITLE
Make file details available from "Disk Images" browser in CONFIG

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-config-old#21]
# Purpose
An option (e.g. via keypress) to expose some metadata about mountable disk images (ATRs, XEXs, etc.) -- I'm thinking modification date/time & file size, but perhaps there are others -- would be nice.

# Motivation
Sometimes users who host TNFS servers create updated versions of disk images, and it's hard to tell if anything has changed (and is worth looking at), unless they include a timestamp in the filename itself (as I've seen with "`weather_YYYYMMDD.xex`").

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
