### ISSUE TITLE
Suggestion: Quick changing of boot disk

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-config-old#27]
From the configuration screen, when drive slots have multiple entries, pressing 'B' on a selected entry swaps that slot with Slot 1.
e.g.:
You're on slot 4 and you press 'B', the contents of slot 1 and slot 4 are swapped.

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
