### ISSUE TITLE
Ability to search a TNFS server for files (client side)

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-config-old#28]
# Purpose
The ability to ask a TNFS server to send back a list of matching files, based on a search criteria.

# Motivation
The ability to more easily find something, when you don't even know where (in the directory hierarchy) it might be stored.

# See also
Would obviously require server side support: https://github.com/FujiNetWIFI/spectranet/issues/4

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
