### ISSUE TITLE
Persist last path for a host slot.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-config-old#36]
### Description

When selecting directories in the Disk Images screen (diskulator_select.c), the current path should be persisted via an Appkey, and re-loaded and used as the current path, when the host slot is selected. If the path no longer exists, it should be erased and replaced with '/'

### Implementation

This can be implemented using the existing AppKey functionality. To do so:

1. Implement load and save appkey functions in src/fuji_sio.c. Use existing functions as templates. The documentation for the appkey functions is here: https://github.com/FujiNetWIFI/fujinet-platformio/wiki/SIO-Commands-for-Device-ID-%2470 (open, close, read, write app key)
2. Set aside an app key ID for config.
3. implement functions in src/diskulator_select.c which set and get this value and put it into the current path.

### Other examples

In fact, you can use the code in appkey-sample quite literally, here: https://github.com/FujiNetWIFI/fujinet-apps/tree/master/appkey-sample

**Comment by mozzwald** [comment]
This repo is being archived, closing all issues. If issue is still present in current firmware, please open a new issue in the new repo https://github.com/FujiNetWIFI/fujinet-config
